# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WacliReadonly < Formula
  desc "Read-only WhatsApp CLI for syncing and searching messages"
  homepage "https://github.com/regalstreak/wacli-readonly"
  version "0.2.2"
  license "MIT"
  depends_on :macos

  url "https://github.com/regalstreak/wacli-readonly/releases/download/v0.2.2/wacli-readonly-macos-universal.tar.gz"
  sha256 "6417c6edcce6b52ada7c2ce3b4e74bbcaf3c5cc817acd17b66582eccf9a3a17d"

  def install
    bin.install "wacli-readonly"
  end
end
