# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WacliReadonly < Formula
  desc "Read-only WhatsApp CLI for syncing and searching messages"
  homepage "https://github.com/regalstreak/wacli-readonly"
  version "0.2.3"
  license "MIT"
  depends_on :macos

  url "https://github.com/regalstreak/wacli-readonly/releases/download/v0.2.3/wacli-readonly-macos-universal.tar.gz"
  sha256 "b1a5628d29d0b97857c8eb2e23da93db8ff246c13a79d04a129bff15dd96427f"

  def install
    bin.install "wacli-readonly"
  end
end
